# Generated by Django 4.0.1 on 2022-01-27 13:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('imageUrl', models.ImageField(blank=True, upload_to='images/%Y/%m')),
                ('newsSite', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('publishedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('events', models.ManyToManyField(to='core.Event')),
                ('launches', models.ManyToManyField(to='core.Launch')),
            ],
        ),
    ]
