# Generated by Django 4.0.1 on 2022-01-27 20:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_image_article),
        ),
    ]
