# Generated by Django 4.0.1 on 2022-01-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
