# Generated by Django 4.0.1 on 2022-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='article',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='events',
            field=models.ManyToManyField(to='core.Event'),
        ),
        migrations.AddField(
            model_name='article',
            name='launches',
            field=models.ManyToManyField(to='core.Launch'),
        ),
    ]
